import type {PlcTag, TabletAppConfig} from '../types/plc';

const bit = (
  name: string,
  address: string,
  description: string,
  writable = false,
): PlcTag => ({name, address, dataType: 'Bool', description, writable});

const word = (
  name: string,
  address: string,
  dataType: PlcTag['dataType'],
  description: string,
  writable = false,
  length?: number,
): PlcTag => ({name, address, dataType, description, writable, length});

export const tabletAppConfig: TabletAppConfig = {
  machineName: 'Gear Line',
  machineCode: 'LINE-HMI',
  lines: [
    {id: 'line1', name: 'Line 1', host: '127.0.0.1', port: 503, slaveId: 1, pollIntervalMs: 100, connectionType: 'TcpAS'},
  ],
  tags: [
    bit('manual.move_x_forward', 'M2000', 'Tiến trục X', true),
    bit('manual.move_x_backward', 'M2001', 'Lùi trục X', true),
    bit('manual.home_x', 'M2002', 'Về góc trục X', true),
    bit('manual.move_x_to_point', 'M2003', 'Chạy điểm vị trí trục X', true),
    word('manual.manual_speed_x', 'D5150', 'Float', 'Tốc độ Manual trục X (mm/s)', true),
    word('manual.move_point_x', 'D5152', 'Float', 'Vị trí chạy điểm trục X (mm)', true),
    word('manual.current_position_x', 'D5154', 'Float', 'Vị trí hiện tại trục X (mm)'),
    bit('manual.is_homing_x', 'M2040', 'Đang về Home X'),
    bit('manual.is_homed_x', 'M2041', 'Đã về Home X'),

    bit('manual.move_y_left', 'M2004', 'Trái trục Y', true),
    bit('manual.move_y_right', 'M2005', 'Phải trục Y', true),
    bit('manual.home_y', 'M2006', 'Về góc trục Y', true),
    bit('manual.move_y_to_point', 'M2007', 'Chạy điểm vị trí trục Y', true),
    word('manual.manual_speed_y', 'D5156', 'Float', 'Tốc độ Manual trục Y (mm/s)', true),
    word('manual.move_point_y', 'D5158', 'Float', 'Vị trí chạy điểm trục Y (mm)', true),
    word('manual.current_position_y', 'D5160', 'Float', 'Vị trí hiện tại trục Y (mm)'),
    bit('manual.is_homing_y', 'M2042', 'Đang về Home Y'),
    bit('manual.is_homed_y', 'M2043', 'Đã về Home Y'),

    bit('manual.move_z_up', 'M2008', 'Lên trục Z', true),
    bit('manual.move_z_down', 'M2009', 'Xuống trục Z', true),
    bit('manual.home_z', 'M2010', 'Về góc trục Z', true),
    bit('manual.move_z_to_point', 'M2011', 'Chạy điểm vị trí trục Z', true),
    word('manual.manual_speed_z', 'D5162', 'Float', 'Tốc độ Manual trục Z (mm/s)', true),
    word('manual.move_point_z', 'D5164', 'Float', 'Vị trí chạy điểm trục Z (mm)', true),
    word('manual.current_position_z', 'D5166', 'Float', 'Vị trí hiện tại trục Z (mm)'),
    bit('manual.is_homing_z', 'M2044', 'Đang về Home Z'),
    bit('manual.is_homed_z', 'M2045', 'Đã về Home Z'),

    bit('manual.change_tool_to_0', 'M2012', 'Xilanh đổi tay tool 0 độ', true),
    bit('manual.change_tool_to_180', 'M2013', 'Xilanh đổi tay tool 180 độ', true),
    bit('manual.clamp_small_part_in', 'M2014', 'Xilanh part nhỏ kẹp', true),
    bit('manual.clamp_small_part_out', 'M2015', 'Xilanh part nhỏ mở', true),
    bit('manual.clamp_large_part_in', 'M2016', 'Xilanh part lớn kẹp', true),
    bit('manual.clamp_large_part_out', 'M2017', 'Xilanh part lớn mở', true),
    bit('manual.rotate_tool_to_0', 'M2018', 'Xilanh xoay tay tool điểm 0', true),
    bit('manual.rotate_tool_to_90', 'M2019', 'Xilanh xoay tay tool quay 90', true),
    bit('manual.clamp_cart_1', 'M2020', 'Xilanh kẹp xe hàng 1', true),
    bit('manual.unclamp_cart_1', 'M2021', 'Xilanh mở xe hàng 1', true),
    bit('manual.clamp_cart_2', 'M2022', 'Xilanh kẹp xe hàng 2', true),
    bit('manual.unclamp_cart_2', 'M2023', 'Xilanh mở xe hàng 2', true),
    bit('manual.home_all', 'M2024', 'Home ALL', true),
    bit('manual.home_cart_1_clamp', 'M2025', 'Home kẹp xe 1', true),
    bit('manual.home_cart_2_clamp', 'M2026', 'Home kẹp xe 2', true),
    bit('manual.home_rotate_cylinder', 'M2027', 'Home xilanh xoay', true),
    bit('manual.home_tool_change_cylinder', 'M2028', 'Home xilanh đảo tool', true),
    bit('manual.home_tool_clamp_cylinder', 'M2029', 'Home xilanh kẹp tay tool', true),

    bit('manual.cart_1_opened_signal', 'M2046', 'Tín hiệu đã mở kẹp xe hàng 1'),
    bit('manual.cart_1_closed_signal', 'M2047', 'Tín hiệu đã kẹp xe hàng 1'),
    bit('manual.cart_2_opened_signal', 'M2048', 'Tín hiệu đã mở kẹp xe hàng 2'),
    bit('manual.cart_2_closed_signal', 'M2049', 'Tín hiệu đã kẹp xe hàng 2'),
    bit('manual.small_part_closed_signal', 'M2050', 'Tín hiệu đã kẹp part nhỏ'),
    bit('manual.small_part_opened_signal', 'M2051', 'Tín hiệu đã mở kẹp part nhỏ'),
    bit('manual.large_part_closed_signal', 'M2052', 'Tín hiệu đã kẹp part lớn'),
    bit('manual.large_part_opened_signal', 'M2053', 'Tín hiệu đã mở kẹp part lớn'),
    bit('manual.rotated_to_0_signal', 'M2054', 'Tín hiệu đã quay về 0'),
    bit('manual.rotated_to_90_signal', 'M2055', 'Tín hiệu đã quay về 90'),
    bit('manual.changed_tool_to_0_signal', 'M2056', 'Tín hiệu đã đổi tay tool 0'),
    bit('manual.changed_tool_to_180_signal', 'M2057', 'Tín hiệu đã đổi tay tool 180'),
    bit('manual.home_cart_1_clamp_done', 'M2058', 'Đã về home kẹp xe hàng 1'),
    bit('manual.home_cart_2_clamp_done', 'M2059', 'Đã về home kẹp xe hàng 2'),
    bit('manual.home_rotate_cylinder_done', 'M2060', 'Đã về home xilanh xoay'),
    bit('manual.home_tool_clamp_done', 'M2061', 'Đã về home kẹp tay tool'),
    bit('manual.home_tool_change_done', 'M2062', 'Đã về home đảo tay tool'),

    bit('output.y0_06', 'D5130.6', 'POWER ON'),
    bit('output.y0_07', 'D5130.7', 'Axis Z ON'),
    bit('input.x0_09', 'D5120.9', 'PRESSURE PNEUMATIC'),
    bit('input.x0_14', 'D5120.14', 'Switch Auto'),
    bit('alarm.estop', 'D5142.0', 'E_EMG'),
    bit('alarm.safety_sensor', 'D5142.15', 'E_SAFETY_SENSOR'),
    bit('alarm.x_limit_negative', 'D5143.0', 'E_LIMIT X -'),
    bit('alarm.x_limit_positive', 'D5143.1', 'E_LIMIT X +'),
    bit('alarm.y_limit_negative', 'D5143.2', 'E_LIMIT Y -'),
    bit('alarm.y_limit_positive', 'D5143.3', 'E_LIMIT Y +'),
    bit('alarm.z_limit_negative', 'D5143.4', 'E_LIMIT Z -'),
    bit('alarm.z_limit_positive', 'D5143.5', 'E_LIMIT Z +'),
    bit('alarm.air_pressure_lost', 'D5143.15', 'E_PRESSURE_AIR'),
    word('data.max_speed_x', 'D21070', 'Float', 'Giới hạn tốc độ trục X'),
    word('data.max_speed_y', 'D21072', 'Float', 'Giới hạn tốc độ trục Y'),
    word('data.max_speed_z', 'D21074', 'Float', 'Giới hạn tốc độ trục Z'),
    word('data.limit_x_positive', 'D21076', 'Float', 'Limit trục X+'),
    word('data.limit_x_negative', 'D21078', 'Float', 'Limit trục X-'),
    word('data.limit_y_positive', 'D21080', 'Float', 'Limit trục Y+'),
    word('data.limit_y_negative', 'D21082', 'Float', 'Limit trục Y-'),
    word('data.limit_z_positive', 'D21084', 'Float', 'Limit trục Z+'),
    word('data.limit_z_negative', 'D21086', 'Float', 'Limit trục Z-'),
  ],
  manualScreen: {
    originActions: [
      {title: 'Home All', subtitle: 'Về gốc toàn bộ 3 trục và cơ cấu xy lanh.', commandTag: 'manual.home_all'},
      {title: 'Home X', subtitle: 'Trục X về vị trí gốc.', commandTag: 'manual.home_x', axisKey: 'axis_x'},
      {title: 'Home Y', subtitle: 'Trục Y về vị trí gốc.', commandTag: 'manual.home_y', axisKey: 'axis_y'},
      {title: 'Home Z', subtitle: 'Trục Z về vị trí gốc.', commandTag: 'manual.home_z', axisKey: 'axis_z'},
      {title: 'Home kẹp xe 1', subtitle: 'Về gốc cơ cấu kẹp xe hàng 1.', commandTag: 'manual.home_cart_1_clamp', doneTag: 'manual.home_cart_1_clamp_done'},
      {title: 'Home kẹp xe 2', subtitle: 'Về gốc cơ cấu kẹp xe hàng 2.', commandTag: 'manual.home_cart_2_clamp', doneTag: 'manual.home_cart_2_clamp_done'},
      {title: 'Home xilanh xoay', subtitle: 'Về gốc cơ cấu xoay 0/90.', commandTag: 'manual.home_rotate_cylinder', doneTag: 'manual.home_rotate_cylinder_done'},
      {title: 'Home đảo tool', subtitle: 'Về gốc cơ cấu đổi tay tool.', commandTag: 'manual.home_tool_change_cylinder', doneTag: 'manual.home_tool_change_done'},
      {title: 'Home kẹp tay tool', subtitle: 'Về gốc cơ cấu kẹp tay tool.', commandTag: 'manual.home_tool_clamp_cylinder', doneTag: 'manual.home_tool_clamp_done'},
    ],
    axes: [
      {
        key: 'axis_x',
        displayName: 'Trục X',
        negativeLabel: 'X -',
        positiveLabel: 'X +',
        negativeJogTag: 'manual.move_x_backward',
        positiveJogTag: 'manual.move_x_forward',
        homeTag: 'manual.home_x',
        moveToPointTag: 'manual.move_x_to_point',
        manualSpeedTag: 'manual.manual_speed_x',
        movePointTag: 'manual.move_point_x',
        currentPositionTag: 'manual.current_position_x',
        isHomingTag: 'manual.is_homing_x',
        isHomedTag: 'manual.is_homed_x',
        negativeLimitAlarmTag: 'alarm.x_limit_negative',
        positiveLimitAlarmTag: 'alarm.x_limit_positive',
        servoTag: 'output.y0_06',
        limitTags: {speedLimitTag: 'data.max_speed_x', negativeLimitTag: 'data.limit_x_negative', positiveLimitTag: 'data.limit_x_positive'},
      },
      {
        key: 'axis_y',
        displayName: 'Trục Y',
        negativeLabel: 'Y -',
        positiveLabel: 'Y +',
        negativeJogTag: 'manual.move_y_left',
        positiveJogTag: 'manual.move_y_right',
        homeTag: 'manual.home_y',
        moveToPointTag: 'manual.move_y_to_point',
        manualSpeedTag: 'manual.manual_speed_y',
        movePointTag: 'manual.move_point_y',
        currentPositionTag: 'manual.current_position_y',
        isHomingTag: 'manual.is_homing_y',
        isHomedTag: 'manual.is_homed_y',
        negativeLimitAlarmTag: 'alarm.y_limit_negative',
        positiveLimitAlarmTag: 'alarm.y_limit_positive',
        servoTag: 'output.y0_06',
        limitTags: {speedLimitTag: 'data.max_speed_y', negativeLimitTag: 'data.limit_y_negative', positiveLimitTag: 'data.limit_y_positive'},
      },
      {
        key: 'axis_z',
        displayName: 'Trục Z',
        negativeLabel: 'Z -',
        positiveLabel: 'Z +',
        negativeJogTag: 'manual.move_z_down',
        positiveJogTag: 'manual.move_z_up',
        homeTag: 'manual.home_z',
        moveToPointTag: 'manual.move_z_to_point',
        manualSpeedTag: 'manual.manual_speed_z',
        movePointTag: 'manual.move_point_z',
        currentPositionTag: 'manual.current_position_z',
        isHomingTag: 'manual.is_homing_z',
        isHomedTag: 'manual.is_homed_z',
        negativeLimitAlarmTag: 'alarm.z_limit_negative',
        positiveLimitAlarmTag: 'alarm.z_limit_positive',
        servoTag: 'output.y0_07',
        limitTags: {speedLimitTag: 'data.max_speed_z', negativeLimitTag: 'data.limit_z_negative', positiveLimitTag: 'data.limit_z_positive'},
      },
    ],
    cylinders: [
      {key: 'change_tool', title: 'Đổi tay tool', subtitle: 'Điều khiển tay tool 0/180 độ.', primaryActionLabel: 'Về 0 độ', secondaryActionLabel: 'Về 180 độ', primaryFeedbackLabel: 'Đã đổi 0', secondaryFeedbackLabel: 'Đã đổi 180', primaryCommandTag: 'manual.change_tool_to_0', secondaryCommandTag: 'manual.change_tool_to_180', primaryFeedbackTag: 'manual.changed_tool_to_0_signal', secondaryFeedbackTag: 'manual.changed_tool_to_180_signal'},
      {key: 'small_part', title: 'Kẹp part nhỏ', subtitle: 'Điều khiển kẹp/mở part nhỏ.', primaryActionLabel: 'Kẹp vào', secondaryActionLabel: 'Mở ra', primaryFeedbackLabel: 'Đã kẹp', secondaryFeedbackLabel: 'Đã mở', primaryCommandTag: 'manual.clamp_small_part_in', secondaryCommandTag: 'manual.clamp_small_part_out', primaryFeedbackTag: 'manual.small_part_closed_signal', secondaryFeedbackTag: 'manual.small_part_opened_signal'},
      {key: 'large_part', title: 'Kẹp part lớn', subtitle: 'Điều khiển kẹp/mở part lớn.', primaryActionLabel: 'Kẹp vào', secondaryActionLabel: 'Mở ra', primaryFeedbackLabel: 'Đã kẹp', secondaryFeedbackLabel: 'Đã mở', primaryCommandTag: 'manual.clamp_large_part_in', secondaryCommandTag: 'manual.clamp_large_part_out', primaryFeedbackTag: 'manual.large_part_closed_signal', secondaryFeedbackTag: 'manual.large_part_opened_signal'},
      {key: 'rotate', title: 'Xy lanh xoay', subtitle: 'Điều khiển góc quay 0 và 90 độ cho tool.', primaryActionLabel: 'Về 0 độ', secondaryActionLabel: 'Đến 90 độ', primaryFeedbackLabel: 'Đã ở 0 độ', secondaryFeedbackLabel: 'Đã ở 90 độ', primaryCommandTag: 'manual.rotate_tool_to_0', secondaryCommandTag: 'manual.rotate_tool_to_90', primaryFeedbackTag: 'manual.rotated_to_0_signal', secondaryFeedbackTag: 'manual.rotated_to_90_signal'},
      {key: 'cart_1', title: 'Kẹp xe hàng 1', subtitle: 'Điều khiển kẹp/mở xe hàng 1.', primaryActionLabel: 'Kẹp xe 1', secondaryActionLabel: 'Mở xe 1', primaryFeedbackLabel: 'Đã kẹp', secondaryFeedbackLabel: 'Đã mở', primaryCommandTag: 'manual.clamp_cart_1', secondaryCommandTag: 'manual.unclamp_cart_1', primaryFeedbackTag: 'manual.cart_1_closed_signal', secondaryFeedbackTag: 'manual.cart_1_opened_signal'},
      {key: 'cart_2', title: 'Kẹp xe hàng 2', subtitle: 'Điều khiển kẹp/mở xe hàng 2.', primaryActionLabel: 'Kẹp xe 2', secondaryActionLabel: 'Mở xe 2', primaryFeedbackLabel: 'Đã kẹp', secondaryFeedbackLabel: 'Đã mở', primaryCommandTag: 'manual.clamp_cart_2', secondaryCommandTag: 'manual.unclamp_cart_2', primaryFeedbackTag: 'manual.cart_2_closed_signal', secondaryFeedbackTag: 'manual.cart_2_opened_signal'},
    ],
    interlockTags: ['alarm.estop', 'alarm.safety_sensor', 'alarm.air_pressure_lost'],
    alarmTags: ['alarm.estop', 'alarm.safety_sensor', 'alarm.air_pressure_lost', 'alarm.x_limit_negative', 'alarm.x_limit_positive', 'alarm.y_limit_negative', 'alarm.y_limit_positive', 'alarm.z_limit_negative', 'alarm.z_limit_positive'],
    autoModeTag: 'input.x0_14',
    pressureHealthyTag: 'input.x0_09',
  },
};

export const tagLookup = new Map(tabletAppConfig.tags.map(tag => [tag.name, tag]));
