import {plcTagByName, plcTags} from './plcTags';
import type {TabletAppConfig} from '../types/plc';

export const tabletAppConfig: TabletAppConfig = {
  machineName: 'Gear Line',
  machineCode: 'LINE-HMI',
  lines: [
    {id: 'line1', name: 'Line 1', host: '127.0.0.1', port: 503, slaveId: 1, pollIntervalMs: 100, connectionType: 'TcpAS'},
  ],
  tags: plcTags,
  manualScreen: {
    originActions: [
      {title: 'Home All', subtitle: 'Về gốc toàn bộ 3 trục và cơ cấu xy lanh.', commandTag: 'manual.home_all'},
      {title: 'Home X', subtitle: 'Trục X về vị trí gốc.', commandTag: 'manual.home_x', axisKey: 'axis_x'},
      {title: 'Home Y', subtitle: 'Trục Y về vị trí gốc.', commandTag: 'manual.home_y', axisKey: 'axis_y'},
      {title: 'Home Z', subtitle: 'Trục Z về vị trí gốc.', commandTag: 'manual.home_z', axisKey: 'axis_z'},
      {title: 'Home kẹp xe 1', subtitle: 'Về gốc cơ cấu kẹp xe hàng 1.', commandTag: 'manual.home_cart_1_clamp', doneTag: 'manual.home_cart_1_clamp_done'},
      {title: 'Home kẹp xe 2', subtitle: 'Về gốc cơ cấu kẹp xe hàng 2.', commandTag: 'manual.home_cart_2_clamp', doneTag: 'manual.home_cart_2_clamp_done'},
      {title: 'Home xilanh xoay', subtitle: 'Về gốc cơ cấu xoay 0/90.', commandTag: 'manual.home_rotate_cylinder', doneTag: 'manual.home_rotate_cylinder_done'},
      {title: 'Home đảo tool', subtitle: 'Về gốc cơ cấu đổi tay tool.', commandTag: 'manual.home_tool_change_cylinder', doneTag: 'manual.home_tool_change_done'},
      {title: 'Home kẹp tay tool', subtitle: 'Về gốc cơ cấu kẹp tay tool.', commandTag: 'manual.home_tool_clamp_cylinder', doneTag: 'manual.home_tool_clamp_done'},
    ],
    axes: [
      {
        key: 'axis_x',
        displayName: 'Trục X',
        negativeLabel: 'X -',
        positiveLabel: 'X +',
        negativeJogTag: 'manual.move_x_backward',
        positiveJogTag: 'manual.move_x_forward',
        homeTag: 'manual.home_x',
        moveToPointTag: 'manual.move_x_to_point',
        manualSpeedTag: 'manual.manual_speed_x',
        movePointTag: 'manual.move_point_x',
        currentPositionTag: 'manual.current_position_x',
        isHomingTag: 'manual.is_homing_x',
        isHomedTag: 'manual.is_homed_x',
        negativeLimitAlarmTag: 'alarm.x_limit_negative',
        positiveLimitAlarmTag: 'alarm.x_limit_positive',
        servoTag: 'output.y06',
        limitTags: {speedLimitTag: 'data.max_speed_x', negativeLimitTag: 'data.limit_x_negative', positiveLimitTag: 'data.limit_x_positive'},
      },
      {
        key: 'axis_y',
        displayName: 'Trục Y',
        negativeLabel: 'Y -',
        positiveLabel: 'Y +',
        negativeJogTag: 'manual.move_y_left',
        positiveJogTag: 'manual.move_y_right',
        homeTag: 'manual.home_y',
        moveToPointTag: 'manual.move_y_to_point',
        manualSpeedTag: 'manual.manual_speed_y',
        movePointTag: 'manual.move_point_y',
        currentPositionTag: 'manual.current_position_y',
        isHomingTag: 'manual.is_homing_y',
        isHomedTag: 'manual.is_homed_y',
        negativeLimitAlarmTag: 'alarm.y_limit_negative',
        positiveLimitAlarmTag: 'alarm.y_limit_positive',
        servoTag: 'output.y06',
        limitTags: {speedLimitTag: 'data.max_speed_y', negativeLimitTag: 'data.limit_y_negative', positiveLimitTag: 'data.limit_y_positive'},
      },
      {
        key: 'axis_z',
        displayName: 'Trục Z',
        negativeLabel: 'Z -',
        positiveLabel: 'Z +',
        negativeJogTag: 'manual.move_z_down',
        positiveJogTag: 'manual.move_z_up',
        homeTag: 'manual.home_z',
        moveToPointTag: 'manual.move_z_to_point',
        manualSpeedTag: 'manual.manual_speed_z',
        movePointTag: 'manual.move_point_z',
        currentPositionTag: 'manual.current_position_z',
        isHomingTag: 'manual.is_homing_z',
        isHomedTag: 'manual.is_homed_z',
        negativeLimitAlarmTag: 'alarm.z_limit_negative',
        positiveLimitAlarmTag: 'alarm.z_limit_positive',
        servoTag: 'output.y07',
        limitTags: {speedLimitTag: 'data.max_speed_z', negativeLimitTag: 'data.limit_z_negative', positiveLimitTag: 'data.limit_z_positive'},
      },
    ],
    cylinders: [
      {key: 'change_tool', title: 'Đổi tay tool', subtitle: 'Điều khiển tay tool 0/180 độ.', primaryActionLabel: 'Về 0 độ', secondaryActionLabel: 'Về 180 độ', primaryFeedbackLabel: 'Đã đổi 0', secondaryFeedbackLabel: 'Đã đổi 180', primaryCommandTag: 'manual.change_tool_to_0', secondaryCommandTag: 'manual.change_tool_to_180', primaryFeedbackTag: 'manual.changed_tool_to_0_signal', secondaryFeedbackTag: 'manual.changed_tool_to_180_signal'},
      {key: 'small_part', title: 'Kẹp part nhỏ', subtitle: 'Điều khiển kẹp/mở part nhỏ.', primaryActionLabel: 'Kẹp vào', secondaryActionLabel: 'Mở ra', primaryFeedbackLabel: 'Đã kẹp', secondaryFeedbackLabel: 'Đã mở', primaryCommandTag: 'manual.clamp_small_part_in', secondaryCommandTag: 'manual.clamp_small_part_out', primaryFeedbackTag: 'manual.small_part_closed_signal', secondaryFeedbackTag: 'manual.small_part_opened_signal'},
      {key: 'large_part', title: 'Kẹp part lớn', subtitle: 'Điều khiển kẹp/mở part lớn.', primaryActionLabel: 'Kẹp vào', secondaryActionLabel: 'Mở ra', primaryFeedbackLabel: 'Đã kẹp', secondaryFeedbackLabel: 'Đã mở', primaryCommandTag: 'manual.clamp_large_part_in', secondaryCommandTag: 'manual.clamp_large_part_out', primaryFeedbackTag: 'manual.large_part_closed_signal', secondaryFeedbackTag: 'manual.large_part_opened_signal'},
      {key: 'rotate', title: 'Xy lanh xoay', subtitle: 'Điều khiển góc quay 0 và 90 độ cho tool.', primaryActionLabel: 'Về 0 độ', secondaryActionLabel: 'Đến 90 độ', primaryFeedbackLabel: 'Đã ở 0 độ', secondaryFeedbackLabel: 'Đã ở 90 độ', primaryCommandTag: 'manual.rotate_tool_to_0', secondaryCommandTag: 'manual.rotate_tool_to_90', primaryFeedbackTag: 'manual.rotated_to_0_signal', secondaryFeedbackTag: 'manual.rotated_to_90_signal'},
      {key: 'cart_1', title: 'Kẹp xe hàng 1', subtitle: 'Điều khiển kẹp/mở xe hàng 1.', primaryActionLabel: 'Kẹp xe 1', secondaryActionLabel: 'Mở xe 1', primaryFeedbackLabel: 'Đã kẹp', secondaryFeedbackLabel: 'Đã mở', primaryCommandTag: 'manual.clamp_cart_1', secondaryCommandTag: 'manual.unclamp_cart_1', primaryFeedbackTag: 'manual.cart_1_closed_signal', secondaryFeedbackTag: 'manual.cart_1_opened_signal'},
      {key: 'cart_2', title: 'Kẹp xe hàng 2', subtitle: 'Điều khiển kẹp/mở xe hàng 2.', primaryActionLabel: 'Kẹp xe 2', secondaryActionLabel: 'Mở xe 2', primaryFeedbackLabel: 'Đã kẹp', secondaryFeedbackLabel: 'Đã mở', primaryCommandTag: 'manual.clamp_cart_2', secondaryCommandTag: 'manual.unclamp_cart_2', primaryFeedbackTag: 'manual.cart_2_closed_signal', secondaryFeedbackTag: 'manual.cart_2_opened_signal'},
    ],
    interlockTags: ['alarm.estop', 'alarm.safety_sensor', 'alarm.air_pressure_lost'],
    alarmTags: ['alarm.estop', 'alarm.safety_sensor', 'alarm.air_pressure_lost', 'alarm.x_limit_negative', 'alarm.x_limit_positive', 'alarm.y_limit_negative', 'alarm.y_limit_positive', 'alarm.z_limit_negative', 'alarm.z_limit_positive'],
    autoModeTag: 'input.x14',
    pressureHealthyTag: 'input.x09',
  },
};

export const tagLookup = plcTagByName;
