// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Server.Api.Data;

#nullable disable

namespace Server.Api.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260810090000_AddMachineJigHeights")]
partial class AddMachineJigHeights
{
}
