import { useEffect, useMemo, useState, useRef } from "react";
import { Modal } from "antd";
import {
  DECLARATION_MODES,
  MACHINE_SLOT_OPTIONS
} from "../constants";
import {
  assignOrderTrayIndexes,
  buildOrderQuantityAllocation,
  buildSelectedOrderSlots,
  buildBusyMachineSlots,
  buildComputedOrders,
  buildGeneratedOrderId,
  buildPersistedComputedOrders,
  buildMachineOptions,
  buildOccupiedStagingSlots,
  buildPreviewSlots,
  buildSelectedMachineStagingSlots,
  buildValidationErrors,
  findLayoutInfo,
  getModelOrderInput,
  getModelTraySize,
  getFirstAvailableSlot,
  getOrderQuantityCap,
  getTotalLayoutCapacity,
  inferShelfLayoutType,
  parseOrdersJson,
  resolveArticleByModelOrder
} from "../utils";

function createOrderKey(offset = 0) {
  return Date.now() + offset;
}

function applyResolvedModelToOrder(order, model, rowIndex, modelOrder) {
  const orderInput = getModelOrderInput(model);
  const isAutoGeneratedOrder = orderInput === 0;
  const articleId = model.modelName;

  return {
    ...order,
    reportModelName: modelOrder,
    modelName: articleId,
    traySize: getModelTraySize(model),
    orderInput,
    isAutoGeneratedOrder,
    orderId: isAutoGeneratedOrder
      ? buildGeneratedOrderId(articleId, rowIndex)
      : (order.isAutoGeneratedOrder ? "" : (order.orderId ?? ""))
  };
}

function clearAutoSplitState(order) {
  return {
    ...order,
    isAutoSplit: false,
    hasAutoSplit: false,
    splitSourceKey: null,
    splitTotalQuantity: null,
    splitQuantities: null,
    splitPartIndex: null,
    splitPartCount: null
  };
}

function removeAutoSplitChildren(orders, sourceKey) {
  return (orders ?? []).filter((order) => !(order.isAutoSplit && order.splitSourceKey === sourceKey));
}

function removeOrderGroup(orders, sourceKey) {
  return (orders ?? []).filter((order) => (
    order.key !== sourceKey && !(order.isAutoSplit && order.splitSourceKey === sourceKey)
  ));
}

function applyQuantityAllocationsToOrders(orders, sourceKey, allocations) {
  const baseOrders = removeAutoSplitChildren(orders, sourceKey);
  const targetIndex = baseOrders.findIndex((item) => item.key === sourceKey);
  if (targetIndex < 0 || allocations.length === 0) {
    return orders;
  }

  const targetOrder = clearAutoSplitState(baseOrders[targetIndex]);
  const splitQuantities = allocations.map((allocation) => allocation.quantity);
  const splitTotalQuantity = splitQuantities.reduce((sum, quantity) => sum + quantity, 0);
  const hasAutoSplit = allocations.length > 1;
  const splitRows = allocations.slice(1).map((allocation, allocationIndex) => ({
    ...targetOrder,
    key: createOrderKey(baseOrders.length + allocationIndex),
    quantity: allocation.quantity,
    trayIndex: null,
    isAutoSplit: true,
    hasAutoSplit: false,
    splitSourceKey: sourceKey,
    splitTotalQuantity,
    splitQuantities,
    splitPartIndex: allocationIndex + 1,
    splitPartCount: allocations.length
  }));

  return [
    ...baseOrders.slice(0, targetIndex),
    {
      ...targetOrder,
      quantity: allocations[0].quantity,
      hasAutoSplit,
      splitTotalQuantity: hasAutoSplit ? splitTotalQuantity : null,
      splitQuantities: hasAutoSplit ? splitQuantities : null,
      splitPartIndex: hasAutoSplit ? 0 : null,
      splitPartCount: hasAutoSplit ? allocations.length : null
    },
    ...splitRows,
    ...baseOrders.slice(targetIndex + 1)
  ];
}

export default function useShelfDeclarationForm({
  selectedMachineId,
  machines,
  models,
  history,
  slotStatuses
}) {
  const [mode, setMode] = useState(DECLARATION_MODES.AGV);
  const [stagingSlotIndex, setStagingSlotIndex] = useState(null);
  const [machineSlotIndex, setMachineSlotIndex] = useState(MACHINE_SLOT_OPTIONS[0]);
  const [shelfLayoutType, setShelfLayoutType] = useState(null);
  const [orders, setOrders] = useState([]);
  const [selectedOrderIndex, setSelectedOrderIndex] = useState(null);
  const isConfirmingQtyRef = useRef(false);
  const hasManualSlotSelectionRef = useRef(false);
  const modelOrderErrorRef = useRef("");

  const machineOptions = useMemo(() => buildMachineOptions(machines), [machines]);
  const modelByArticleId = useMemo(() => {
    const map = new Map();
    models.filter((model) => model && !model.isDeleted).forEach((model) => {
      if (model.modelName) {
        map.set(model.modelName.trim().toLowerCase(), model);
      }
    });
    return map;
  }, [models]);
  const knownModelNames = useMemo(() => new Set(modelByArticleId.keys()), [modelByArticleId]);
  const selectedMachineLabel = useMemo(
    () => machineOptions.find((item) => item.value === selectedMachineId)?.label ?? "Chưa chọn máy",
    [machineOptions, selectedMachineId]
  );

  const autoShelfLayoutType = useMemo(
    () => inferShelfLayoutType(orders),
    [orders]
  );
  const layoutInfo = useMemo(() => findLayoutInfo(shelfLayoutType), [shelfLayoutType]);
  const ordersWithTrayIndexes = useMemo(
    () => assignOrderTrayIndexes(layoutInfo, orders),
    [layoutInfo, orders]
  );

  const maxTray1 = layoutInfo?.tray1Rows ?? 0;
  const maxTray2 = layoutInfo?.tray2Rows ?? 0;
  const maxTotal = maxTray1 + maxTray2;
  const totalCapacity = useMemo(() => getTotalLayoutCapacity(layoutInfo), [layoutInfo]);

  const orderQuantityCaps = useMemo(
    () => ordersWithTrayIndexes.map((_, index) => getOrderQuantityCap(layoutInfo, ordersWithTrayIndexes, index)),
    [layoutInfo, ordersWithTrayIndexes]
  );

  const computedOrders = useMemo(
    () => buildComputedOrders(layoutInfo, ordersWithTrayIndexes),
    [layoutInfo, ordersWithTrayIndexes]
  );

  const usedRows = useMemo(
    () => computedOrders.reduce((sum, order) => sum + (order.rowsUsed ?? 0), 0),
    [computedOrders]
  );
  const hasUnplacedTypedOrder = useMemo(
    () => ordersWithTrayIndexes.some((order) => order.traySize && !order.trayIndex),
    [ordersWithTrayIndexes]
  );

  const preview = useMemo(
    () => buildPreviewSlots(layoutInfo, computedOrders),
    [computedOrders, layoutInfo]
  );

  const occupiedStagingSlots = useMemo(
    () => buildOccupiedStagingSlots(slotStatuses),
    [slotStatuses]
  );

  const busyMachineSlots = useMemo(
    () => buildBusyMachineSlots(history),
    [history]
  );

  const selectedPreviewDeclaration = useMemo(() => {
    if (mode === DECLARATION_MODES.AGV) {
      if (!Number.isFinite(stagingSlotIndex) || !occupiedStagingSlots.has(stagingSlotIndex)) {
        return null;
      }

      return history.find((item) => (
        item.mode === DECLARATION_MODES.AGV
        && item.stagingSlotIndex === stagingSlotIndex
        && item.ordersJson
        && Number.isFinite(item.shelfLayoutType)
      )) ?? null;
    }

    if (mode === DECLARATION_MODES.MANUAL && busyMachineSlots.has(machineSlotIndex)) {
      const declaration = busyMachineSlots.get(machineSlotIndex);
      return declaration?.ordersJson && Number.isFinite(declaration.shelfLayoutType)
        ? declaration
        : null;
    }

    return null;
  }, [busyMachineSlots, history, machineSlotIndex, mode, occupiedStagingSlots, stagingSlotIndex]);

  const shouldUseDeclarationPreview = useMemo(
    () => Boolean(selectedPreviewDeclaration),
    [selectedPreviewDeclaration]
  );

  const displayShelfLayoutType = useMemo(() => {
    if (shouldUseDeclarationPreview) {
      return selectedPreviewDeclaration?.shelfLayoutType ?? shelfLayoutType;
    }

    return shelfLayoutType;
  }, [selectedPreviewDeclaration, shelfLayoutType, shouldUseDeclarationPreview]);

  const displayLayoutInfo = useMemo(() => {
    if (shouldUseDeclarationPreview) {
      return findLayoutInfo(selectedPreviewDeclaration.shelfLayoutType);
    }

    return layoutInfo;
  }, [layoutInfo, selectedPreviewDeclaration, shouldUseDeclarationPreview]);

  const displayComputedOrders = useMemo(() => {
    if (shouldUseDeclarationPreview) {
      return buildPersistedComputedOrders(
        displayLayoutInfo,
        parseOrdersJson(selectedPreviewDeclaration.ordersJson)
      );
    }

    return computedOrders;
  }, [computedOrders, displayLayoutInfo, selectedPreviewDeclaration, shouldUseDeclarationPreview]);

  const displayPreview = useMemo(() => {
    if (shouldUseDeclarationPreview) {
      return buildPreviewSlots(displayLayoutInfo, displayComputedOrders);
    }

    return preview;
  }, [displayComputedOrders, displayLayoutInfo, preview, shouldUseDeclarationPreview]);

  const orderRows = useMemo(
    () => (shouldUseDeclarationPreview ? displayComputedOrders : computedOrders),
    [computedOrders, displayComputedOrders, shouldUseDeclarationPreview]
  );

  const selectedMachineStagingSlots = useMemo(
    () => buildSelectedMachineStagingSlots(machines, selectedMachineId),
    [machines, selectedMachineId]
  );

  const isBusyLocked = useMemo(() => {
    if (mode === DECLARATION_MODES.AGV) {
      return Number.isFinite(stagingSlotIndex) && occupiedStagingSlots.has(stagingSlotIndex);
    }

    if (mode === DECLARATION_MODES.MANUAL) {
      return busyMachineSlots.has(machineSlotIndex);
    }

    return false;
  }, [busyMachineSlots, machineSlotIndex, mode, occupiedStagingSlots, stagingSlotIndex]);

  const canAddOrder = !isBusyLocked && (
    orders.length === 0
    || (Boolean(layoutInfo) && !hasUnplacedTypedOrder && usedRows < maxTotal)
  );

  const selectedOrderSlots = useMemo(
    () => buildSelectedOrderSlots(displayLayoutInfo, orderRows, selectedOrderIndex),
    [displayLayoutInfo, orderRows, selectedOrderIndex]
  );

  useEffect(() => {
    if (mode !== DECLARATION_MODES.AGV) {
      return;
    }

    const ownedSlots = Array.from(selectedMachineStagingSlots);
    const nextPreferredSlot = ownedSlots.length
      ? getFirstAvailableSlot(ownedSlots, occupiedStagingSlots, ownedSlots[0])
      : null;

    if (!selectedMachineStagingSlots.has(stagingSlotIndex)) {
      setStagingSlotIndex(nextPreferredSlot);
    }
  }, [mode, occupiedStagingSlots, selectedMachineStagingSlots, stagingSlotIndex]);

  useEffect(() => {
    if (mode !== DECLARATION_MODES.MANUAL) {
      return;
    }

    if (!hasManualSlotSelectionRef.current && busyMachineSlots.has(machineSlotIndex)) {
      setMachineSlotIndex(getFirstAvailableSlot(MACHINE_SLOT_OPTIONS, busyMachineSlots, MACHINE_SLOT_OPTIONS[0]));
    }
  }, [busyMachineSlots, machineSlotIndex, mode]);

  useEffect(() => {
    if (shelfLayoutType !== autoShelfLayoutType) {
      setShelfLayoutType(autoShelfLayoutType);
    }
  }, [autoShelfLayoutType, shelfLayoutType]);

  useEffect(() => {
    hasManualSlotSelectionRef.current = false;
    setOrders([]);
    setSelectedOrderIndex(null);
  }, [mode]);

  const selectMachineSlotIndex = (slotIndex) => {
    hasManualSlotSelectionRef.current = true;
    setMachineSlotIndex(slotIndex);
  };

  useEffect(() => {
    if (!Number.isInteger(selectedOrderIndex)) {
      return;
    }

    if (selectedOrderIndex >= orderRows.length) {
      setSelectedOrderIndex(orderRows.length > 0 ? orderRows.length - 1 : null);
    }
  }, [orderRows.length, selectedOrderIndex]);

  const validationErrors = useMemo(() => buildValidationErrors({
    selectedMachineId,
    shelfLayoutType,
    ordersLength: orders.length,
    computedOrders,
    previewErrors: preview.errors,
    mode,
    stagingSlotIndex,
    machineSlotIndex,
    selectedMachineStagingSlots,
    occupiedStagingSlots,
    busyMachineSlots,
    knownModelNames
  }), [
    busyMachineSlots,
    computedOrders,
    machineSlotIndex,
    mode,
    occupiedStagingSlots,
    orders.length,
    preview.errors,
    selectedMachineStagingSlots,
    selectedMachineId,
    shelfLayoutType,
    stagingSlotIndex,
    knownModelNames
  ]);

  const canSubmit = validationErrors.length === 0;

  const addOrder = () => {
    if (!canAddOrder) {
      return;
    }

    setOrders((prev) => {
      const nextOrder = {
        key: createOrderKey(prev.length),
        orderId: "",
        modelName: "",
        reportModelName: "",
        orderInput: null,
        isAutoGeneratedOrder: false,
        quantity: null,
        traySize: null,
        trayIndex: null
      };
      setSelectedOrderIndex(prev.length);
      return [...prev, nextOrder];
    });
  };

  const updateOrder = (key, field, value) => {
    if (isBusyLocked) {
      return;
    }

    if (field !== "quantity") {
      setOrders((prev) => {
        const baseOrders = removeAutoSplitChildren(prev, key);
        const targetIndex = baseOrders.findIndex((item) => item.key === key);
        if (targetIndex < 0) {
          return prev;
        }

        if (field === "modelName") {
          const articleId = value || "";
          const selectedModel = modelByArticleId.get(articleId.trim().toLowerCase());
          return baseOrders.map((item) => {
            if (item.key !== key) {
              return item;
            }

            const baseItem = clearAutoSplitState(item);
            return selectedModel
              ? applyResolvedModelToOrder(baseItem, selectedModel, targetIndex, baseItem.reportModelName || articleId)
              : {
                ...baseItem,
                orderId: "",
                modelName: articleId,
                traySize: null,
                orderInput: null,
                isAutoGeneratedOrder: false
              };
          });
        }

        if (field === "reportModelName") {
          const modelOrder = value || "";
          const resolved = resolveArticleByModelOrder(models, modelOrder);
          const selectedModel = resolved.status === "resolved" ? resolved.model : null;
          modelOrderErrorRef.current = "";

          return baseOrders.map((item) => {
            if (item.key !== key) {
              return item;
            }

            const baseItem = clearAutoSplitState(item);
            return selectedModel
              ? applyResolvedModelToOrder(baseItem, selectedModel, targetIndex, modelOrder)
              : {
                ...baseItem,
                orderId: "",
                reportModelName: modelOrder,
                modelName: "",
                traySize: null,
                orderInput: null,
                isAutoGeneratedOrder: false
              };
          });
        }

        if (field === "orderId") {
          return baseOrders.map((item) => (
            item.key === key
              ? { ...clearAutoSplitState(item), orderId: value || "", isAutoGeneratedOrder: false }
              : item
          ));
        }

        return baseOrders.map((item) => (
          item.key === key ? { ...clearAutoSplitState(item), [field]: value } : item
        ));
      });
      return;
    }

    const baseOrdersForPlan = removeAutoSplitChildren(orders, key);
    const targetIndex = baseOrdersForPlan.findIndex((item) => item.key === key);
    if (targetIndex < 0) return;

    if (value == null || value === "") {
      setOrders((prev) => removeAutoSplitChildren(prev, key).map((item) => (
        item.key === key ? { ...clearAutoSplitState(item), quantity: null } : item
      )));
      return;
    }

    const requestedQty = Math.max(1, Number(value) || 1);
    const quantityPlan = buildOrderQuantityAllocation(layoutInfo, baseOrdersForPlan, targetIndex, requestedQty);
    const maxAllowed = quantityPlan.maxAllowed || 0;

    const applyQuantityPlan = (allocations) => {
      setOrders((prev) => applyQuantityAllocationsToOrders(prev, key, allocations));
    };

    if (maxAllowed === 0 || requestedQty > maxAllowed) {
      if (isConfirmingQtyRef.current) return;
      isConfirmingQtyRef.current = true;

      Modal.confirm({
        title: "Vượt giới hạn sức chứa",
        content: `Số lượng nhập vào (${requestedQty}) vượt quá sức chứa còn lại của các khay cùng loại (${maxAllowed}). Bạn có muốn tự động điều chỉnh về ${maxAllowed} không?`,
        okText: "Đồng ý",
        cancelText: "Hủy",
        onOk: () => {
          isConfirmingQtyRef.current = false;
          applyQuantityPlan(quantityPlan.allocations.length ? quantityPlan.allocations : [{ quantity: maxAllowed }]);
        },
        onCancel: () => {
          isConfirmingQtyRef.current = false;
          setOrders((prev) => removeOrderGroup(prev, key));
          setSelectedOrderIndex(null);
        }
      });
    } else {
      applyQuantityPlan(quantityPlan.allocations.length ? quantityPlan.allocations : [{ quantity: requestedQty }]);
    }
  };

  const showModelOrderLookupError = (modelOrder, status, matches = []) => {
    const normalized = (modelOrder || "").trim();
    const dedupeKey = `${status}:${normalized}`;
    if (modelOrderErrorRef.current === dedupeKey) {
      return;
    }

    modelOrderErrorRef.current = dedupeKey;

    if (status === "ambiguous") {
      Modal.error({
        title: "Article ID chưa đủ rõ",
        content: `Article ID "${normalized}" đang khớp nhiều ID (${matches.slice(0, 3).map((model) => model.modelName).join(", ")}). Vui lòng nhập rõ hơn.`
      });
      return;
    }

    if (status === "inactive") {
      Modal.error({
        title: "Model đang Deactive",
        content: `Article ID "${normalized}" thuộc model đang Deactive. Vui lòng Active model trước khi khai báo order.`
      });
      return;
    }

    Modal.error({
      title: "Không tìm thấy ID",
      content: `Article ID "${normalized}" chưa có ID trong cấu hình model. Vui lòng tạo model tương ứng trước khi khai báo.`
    });
  };

  const resolveModelOrder = (key, options = {}) => {
    const target = orders.find((item) => item.key === key);
    if (!target || isBusyLocked) {
      return false;
    }

    const modelOrder = options.modelOrder ?? target.reportModelName ?? "";
    if (!modelOrder.trim()) {
      if (options.showError) {
        showModelOrderLookupError("trống", "not_found");
      }
      return false;
    }

    if (target.modelName && knownModelNames.has(target.modelName.trim().toLowerCase())) {
      const selectedModel = modelByArticleId.get(target.modelName.trim().toLowerCase());
      const orderInput = getModelOrderInput(selectedModel ?? target);
      if (selectedModel && orderInput === 0 && !target.orderId?.trim()) {
        setOrders((prev) => prev.map((item, index) => (
          item.key === key
            ? applyResolvedModelToOrder(item, selectedModel, index, modelOrder)
            : item
        )));
      }
      modelOrderErrorRef.current = "";
      return { resolved: true, orderInput };
    }

    const resolved = resolveArticleByModelOrder(models, modelOrder);
    if (resolved.status === "resolved") {
      const articleId = resolved.model.modelName;
      setOrders((prev) => prev.map((item) => (
        item.key === key
          ? applyResolvedModelToOrder(item, resolved.model, prev.findIndex((order) => order.key === key), modelOrder)
          : item
      )));
      modelOrderErrorRef.current = "";
      return { resolved: true, orderInput: getModelOrderInput(resolved.model), articleId };
    }

    showModelOrderLookupError(modelOrder, resolved.status, resolved.matches);
    return false;
  };

  const ensureModelOrdersResolved = () => {
    const unresolved = orders.find((order) => (
      order.reportModelName?.trim()
      && (!order.modelName?.trim() || !knownModelNames.has(order.modelName.trim().toLowerCase()))
    ));

    if (!unresolved) {
      return true;
    }

    return resolveModelOrder(unresolved.key, { showError: true });
  };

  const removeOrder = (index) => {
    setOrders((prev) => {
      const target = prev[index];
      if (!target) {
        return prev;
      }

      if (target.isAutoSplit) {
        return prev;
      }

      return prev.filter((order, itemIndex) => (
        itemIndex !== index && !(order.isAutoSplit && order.splitSourceKey === target.key)
      ));
    });
    setSelectedOrderIndex((current) => {
      if (!Number.isInteger(current)) {
        return current;
      }

      if (current === index) {
        return null;
      }

      if (current > index) {
        return current - 1;
      }

      return current;
    });
  };

  const resetMachineScopedState = () => {
    setOrders([]);
    setShelfLayoutType(null);
    setSelectedOrderIndex(null);
  };

  const resetAfterSubmit = () => {
    setOrders([]);
    setShelfLayoutType(null);
    setSelectedOrderIndex(null);
  };

  return {
    selectedMachineLabel,
    machineOptions,
    mode,
    shelfLayoutType: displayShelfLayoutType,
    stagingSlotIndex,
    machineSlotIndex,
    orders,
    layoutInfo,
    maxTotal,
    computedOrders,
    orderRows,
    orderQuantityCaps,
    preview,
    totalCapacity,
    canAddOrder,
    displayShelfLayoutType,
    displayLayoutInfo,
    displayComputedOrders,
    displayPreview,
    occupiedStagingSlots,
    selectedMachineStagingSlots,
    busyMachineSlots,
    isBusyLocked,
    selectedOrderIndex,
    selectedOrderSlots,
    validationErrors,
    canSubmit,
    setMode,
    setSelectedOrderIndex,
    setShelfLayoutType,
    setStagingSlotIndex,
    setMachineSlotIndex: selectMachineSlotIndex,
    addOrder,
    updateOrder,
    resolveModelOrder,
    ensureModelOrdersResolved,
    removeOrder,
    resetMachineScopedState,
    resetAfterSubmit
  };
}
