import { useEffect, useMemo, useRef, useState } from "react";
import { Modal } from "antd";
import { DECLARATION_MODES, MACHINE_SLOT_OPTIONS } from "../constants";
import {
  allocateCartOrders,
  buildCartPreviewFromPlacements,
  flattenCartPlacements,
  getModelInputThickness,
  getModelJigType
} from "../cartUtils";
import {
  buildBusyMachineSlots,
  buildGeneratedOrderId,
  buildMachineOptions,
  buildOccupiedStagingSlots,
  buildSelectedMachineStagingSlots,
  getFirstAvailableSlot,
  parseOrdersJson,
  resolveArticleByModelOrder
} from "../utils";

function createOrderKey(offset = 0) {
  return Date.now() + offset;
}

function clearOrderAllocation(order) {
  return {
    ...order,
    placements: undefined,
    cartPositionIndex: null,
    allocatedQuantity: 0,
    overflowQuantity: 0,
    maxQty: 0
  };
}

function applyResolvedModelToOrder(order, model, rowIndex, modelOrder) {
  const orderInput = Number(model?.orderInput ?? 1) === 0 ? 0 : 1;
  const articleId = model.modelName;
  return {
    ...clearOrderAllocation(order),
    reportModelName: modelOrder,
    modelName: articleId,
    jigType: getModelJigType(model),
    inputThickness: getModelInputThickness(model),
    orderInput,
    isAutoGeneratedOrder: orderInput === 0,
    orderId: orderInput === 0
      ? buildGeneratedOrderId(articleId, rowIndex)
      : (order.isAutoGeneratedOrder ? "" : (order.orderId ?? ""))
  };
}

function buildValidationErrors({
  selectedMachineId,
  orders,
  computedOrders,
  allocationErrors,
  knownModelNames,
  mode,
  stagingSlotIndex,
  machineSlotIndex,
  selectedMachineStagingSlots,
  occupiedStagingSlots,
  busyMachineSlots
}) {
  const errors = [];
  if (!selectedMachineId) errors.push("Chưa chọn máy.");
  if (!orders.length) errors.push("Cần thêm ít nhất một order.");
  if (mode === DECLARATION_MODES.AGV) {
    if (!Number.isFinite(stagingSlotIndex)) errors.push("Cần chọn staging slot.");
    else if (!selectedMachineStagingSlots.has(stagingSlotIndex)) errors.push("Staging slot không thuộc máy đã chọn.");
    else if (occupiedStagingSlots.has(stagingSlotIndex)) errors.push("Staging slot đang có khai báo hoạt động.");
  } else if (busyMachineSlots.has(machineSlotIndex)) {
    errors.push("Machine slot đang có khai báo hoạt động.");
  }

  orders.forEach((order, index) => {
    if (!order.modelName?.trim() || !knownModelNames.has(order.modelName.trim().toLowerCase())) {
      errors.push(`Order #${index + 1}: Article ID chưa hợp lệ.`);
    }
    if (Number(order.orderInput ?? 1) !== 0 && !order.orderId?.trim()) {
      errors.push(`Order #${index + 1}: cần nhập Order ID.`);
    }
    if (!Number.isInteger(Number(order.quantity)) || Number(order.quantity) < 1) {
      errors.push(`Order #${index + 1}: số lượng phải lớn hơn 0.`);
    }
  });

  errors.push(...allocationErrors);
  computedOrders.forEach((order, index) => {
    if (order.overflowQuantity > 0) {
      errors.push(`Order #${index + 1}: còn ${order.overflowQuantity} sản phẩm chưa xếp được.`);
    }
  });
  return Array.from(new Set(errors));
}

export default function useShelfDeclarationForm({
  selectedMachineId,
  machines,
  models,
  history,
  slotStatuses
}) {
  const [mode, setMode] = useState(DECLARATION_MODES.AGV);
  const [stagingSlotIndex, setStagingSlotIndex] = useState(null);
  const [machineSlotIndex, setMachineSlotIndex] = useState(MACHINE_SLOT_OPTIONS[0]);
  const [orders, setOrders] = useState([]);
  const [selectedOrderIndex, setSelectedOrderIndex] = useState(null);
  const hasManualSlotSelectionRef = useRef(false);
  const modelOrderErrorRef = useRef("");

  const selectedMachine = useMemo(
    () => machines.find((machine) => machine.machineId === selectedMachineId) ?? null,
    [machines, selectedMachineId]
  );
  const machineOptions = useMemo(() => buildMachineOptions(machines), [machines]);
  const modelByArticleId = useMemo(() => {
    const map = new Map();
    models.filter((model) => model && !model.isDeleted).forEach((model) => {
      if (model.modelName) map.set(model.modelName.trim().toLowerCase(), model);
    });
    return map;
  }, [models]);
  const knownModelNames = useMemo(() => new Set(modelByArticleId.keys()), [modelByArticleId]);
  const selectedMachineLabel = useMemo(
    () => machineOptions.find((item) => item.value === selectedMachineId)?.label ?? "Chưa chọn máy",
    [machineOptions, selectedMachineId]
  );

  const allocation = useMemo(
    () => allocateCartOrders(orders, selectedMachine),
    [orders, selectedMachine]
  );
  const computedOrders = allocation.computedOrders;
  const orderRows = computedOrders;
  const placementRows = useMemo(() => flattenCartPlacements(computedOrders), [computedOrders]);
  const cartPreview = allocation.positions;
  const totalCapacity = allocation.totalCapacity;
  const orderQuantityCaps = computedOrders.map((order) => order.maxQty ?? 0);

  const occupiedStagingSlots = useMemo(() => buildOccupiedStagingSlots(slotStatuses), [slotStatuses]);
  const busyMachineSlots = useMemo(() => buildBusyMachineSlots(history), [history]);
  const selectedMachineStagingSlots = useMemo(
    () => buildSelectedMachineStagingSlots(machines, selectedMachineId),
    [machines, selectedMachineId]
  );

  const selectedPreviewDeclaration = useMemo(() => {
    if (mode === DECLARATION_MODES.AGV) {
      if (!Number.isFinite(stagingSlotIndex) || !occupiedStagingSlots.has(stagingSlotIndex)) return null;
      return history.find((item) => item.mode === DECLARATION_MODES.AGV
        && item.stagingSlotIndex === stagingSlotIndex
        && item.ordersJson) ?? null;
    }

    if (mode === DECLARATION_MODES.MANUAL && busyMachineSlots.has(machineSlotIndex)) {
      const declaration = busyMachineSlots.get(machineSlotIndex);
      return declaration?.ordersJson ? declaration : null;
    }
    return null;
  }, [busyMachineSlots, history, machineSlotIndex, mode, occupiedStagingSlots, stagingSlotIndex]);

  const shouldUseDeclarationPreview = Boolean(selectedPreviewDeclaration);
  const persistedPreviewOrders = useMemo(() => (
    shouldUseDeclarationPreview
      ? parseOrdersJson(selectedPreviewDeclaration.ordersJson).map((order, index) => {
        const key = `persisted-${order.orderSequence ?? index + 1}-${index}`;
        return {
          ...order,
          key,
          orderKey: key,
          placements: [{
            ...order,
            key: `${key}-placement`,
            orderKey: key,
            cartPositionIndex: order.cartPositionIndex ?? 0,
            quantity: order.quantity,
            maxQty: order.maxQty ?? order.jigCapacity ?? 0
          }]
        };
      })
      : []
  ), [selectedPreviewDeclaration, shouldUseDeclarationPreview]);
  const displayComputedOrders = shouldUseDeclarationPreview ? persistedPreviewOrders : computedOrders;
  const displayCartPreview = useMemo(() => (
    shouldUseDeclarationPreview
      ? buildCartPreviewFromPlacements(persistedPreviewOrders)
      : cartPreview
  ), [cartPreview, persistedPreviewOrders, shouldUseDeclarationPreview]);

  const isBusyLocked = useMemo(() => {
    if (mode === DECLARATION_MODES.AGV) {
      return Number.isFinite(stagingSlotIndex) && occupiedStagingSlots.has(stagingSlotIndex);
    }
    return busyMachineSlots.has(machineSlotIndex);
  }, [busyMachineSlots, machineSlotIndex, mode, occupiedStagingSlots, stagingSlotIndex]);

  const canAddOrder = !isBusyLocked && (
    orders.length === 0 || allocation.positions.some((position) => position.jigType === 0 || position.remaining > 0)
  );
  const selectedOrderSlots = useMemo(() => {
    const selected = displayComputedOrders[selectedOrderIndex];
    return {
      highlightedPlacements: new Set((selected?.placements ?? []).map((item) => item.orderKey ?? item.key))
    };
  }, [displayComputedOrders, selectedOrderIndex]);

  useEffect(() => {
    if (mode !== DECLARATION_MODES.AGV) return;
    const ownedSlots = Array.from(selectedMachineStagingSlots);
    const nextSlot = ownedSlots.length
      ? getFirstAvailableSlot(ownedSlots, occupiedStagingSlots, ownedSlots[0])
      : null;
    if (!selectedMachineStagingSlots.has(stagingSlotIndex)) setStagingSlotIndex(nextSlot);
  }, [mode, occupiedStagingSlots, selectedMachineStagingSlots, stagingSlotIndex]);

  useEffect(() => {
    if (mode === DECLARATION_MODES.MANUAL
      && !hasManualSlotSelectionRef.current
      && busyMachineSlots.has(machineSlotIndex)) {
      setMachineSlotIndex(getFirstAvailableSlot(MACHINE_SLOT_OPTIONS, busyMachineSlots, MACHINE_SLOT_OPTIONS[0]));
    }
  }, [busyMachineSlots, machineSlotIndex, mode]);

  useEffect(() => {
    hasManualSlotSelectionRef.current = false;
    setOrders([]);
    setSelectedOrderIndex(null);
  }, [mode]);

  useEffect(() => {
    if (selectedOrderIndex >= displayComputedOrders.length) {
      setSelectedOrderIndex(displayComputedOrders.length > 0 ? displayComputedOrders.length - 1 : null);
    }
  }, [displayComputedOrders.length, selectedOrderIndex]);

  const validationErrors = useMemo(() => {
    if (shouldUseDeclarationPreview) {
      return ["Slot đang có khai báo chưa chạy."];
    }

    return buildValidationErrors({
      selectedMachineId,
      orders,
      computedOrders,
      allocationErrors: allocation.errors,
      knownModelNames,
      mode,
      stagingSlotIndex,
      machineSlotIndex,
      selectedMachineStagingSlots,
      occupiedStagingSlots,
      busyMachineSlots
    });
  }, [allocation.errors, busyMachineSlots, computedOrders, knownModelNames, machineSlotIndex, mode,
    occupiedStagingSlots, orders, selectedMachineId, selectedMachineStagingSlots, shouldUseDeclarationPreview,
    stagingSlotIndex]);

  const addOrder = () => {
    if (!canAddOrder) return;
    setOrders((previous) => {
      const next = {
        key: createOrderKey(previous.length),
        orderId: "",
        modelName: "",
        reportModelName: "",
        orderInput: null,
        isAutoGeneratedOrder: false,
        quantity: null,
        jigType: 0,
        inputThickness: 0,
        cartPositionIndex: null
      };
      setSelectedOrderIndex(previous.length);
      return [...previous, next];
    });
  };

  const updateOrder = (key, field, value) => {
    if (isBusyLocked) return;
    setOrders((previous) => previous.map((item, index) => {
      if (item.key !== key) return item;
      if (field === "modelName") {
        const model = modelByArticleId.get((value || "").trim().toLowerCase());
        return model ? applyResolvedModelToOrder(item, model, index, item.reportModelName || value) : {
          ...clearOrderAllocation(item), modelName: value || "", orderId: "", jigType: 0, inputThickness: 0
        };
      }
      if (field === "reportModelName") {
        const resolved = resolveArticleByModelOrder(models, value || "");
        return resolved.status === "resolved"
          ? applyResolvedModelToOrder(item, resolved.model, index, value || "")
          : { ...clearOrderAllocation(item), reportModelName: value || "", modelName: "", jigType: 0, inputThickness: 0 };
      }
      return { ...clearOrderAllocation(item), [field]: value };
    }));
  };

  const showModelOrderLookupError = (modelOrder, status, matches = []) => {
    const normalized = (modelOrder || "").trim();
    const dedupeKey = `${status}:${normalized}`;
    if (modelOrderErrorRef.current === dedupeKey) return;
    modelOrderErrorRef.current = dedupeKey;
    if (status === "ambiguous") {
      Modal.error({ title: "Article ID chưa đủ rõ", content: `Article ID "${normalized}" khớp nhiều ID (${matches.slice(0, 3).map((model) => model.modelName).join(", ")}).` });
      return;
    }
    Modal.error({ title: "Không tìm thấy ID", content: `Article ID "${normalized}" chưa có trong cấu hình model.` });
  };

  const resolveModelOrder = (key, options = {}) => {
    const target = orders.find((item) => item.key === key);
    if (!target || isBusyLocked) return false;
    const modelOrder = options.modelOrder ?? target.reportModelName ?? "";
    const resolved = resolveArticleByModelOrder(models, modelOrder);
    if (resolved.status !== "resolved") {
      if (options.showError) showModelOrderLookupError(modelOrder, resolved.status, resolved.matches);
      return false;
    }
    setOrders((previous) => previous.map((item, index) => (
      item.key === key ? applyResolvedModelToOrder(item, resolved.model, index, modelOrder) : item
    )));
    modelOrderErrorRef.current = "";
    return { resolved: true, orderInput: Number(resolved.model.orderInput ?? 1) === 0 ? 0 : 1 };
  };

  const ensureModelOrdersResolved = () => {
    const unresolved = orders.find((order) => order.reportModelName?.trim()
      && (!order.modelName?.trim() || !knownModelNames.has(order.modelName.trim().toLowerCase())));
    return unresolved ? resolveModelOrder(unresolved.key, { showError: true }) : true;
  };

  const removeOrder = (index) => {
    setOrders((previous) => previous.filter((_, itemIndex) => itemIndex !== index));
    setSelectedOrderIndex((current) => current === index ? null : current > index ? current - 1 : current);
  };

  const selectMachineSlotIndex = (slotIndex) => {
    hasManualSlotSelectionRef.current = true;
    setMachineSlotIndex(slotIndex);
  };

  const resetState = () => {
    setOrders([]);
    setSelectedOrderIndex(null);
  };

  return {
    selectedMachineLabel,
    machineOptions,
    mode,
    stagingSlotIndex,
    machineSlotIndex,
    orders,
    selectedMachine,
    maxTotal: 4,
    totalCapacity,
    computedOrders,
    orderRows,
    placementRows,
    orderQuantityCaps,
    cartPreview,
    displayComputedOrders,
    displayCartPreview,
    canAddOrder,
    occupiedStagingSlots,
    selectedMachineStagingSlots,
    busyMachineSlots,
    isBusyLocked,
    selectedOrderIndex,
    selectedOrderSlots,
    validationErrors,
    canSubmit: validationErrors.length === 0,
    setMode,
    setSelectedOrderIndex,
    setStagingSlotIndex,
    setMachineSlotIndex: selectMachineSlotIndex,
    addOrder,
    updateOrder,
    resolveModelOrder,
    ensureModelOrdersResolved,
    removeOrder,
    resetMachineScopedState: resetState,
    resetAfterSubmit: resetState
  };
}
