/**
 * @typedef {Object} OrderDraft
 * @property {number|string} key
 * @property {string} orderId
 * @property {string} modelName
 * @property {string=} reportModelName
 * @property {0|1|null=} orderInput
 * @property {boolean=} isAutoGeneratedOrder
 * @property {boolean=} isAutoSplit
 * @property {boolean=} hasAutoSplit
 * @property {number|string|null=} splitSourceKey
 * @property {number|null=} splitTotalQuantity
 * @property {number[]|null=} splitQuantities
 * @property {number|null=} splitPartIndex
 * @property {number|null=} splitPartCount
 * @property {number|null} quantity
 * @property {"small"|"large"|null=} traySize
 */

/**
 * @typedef {OrderDraft & {
 *   orderSequence: number,
 *   trayIndex: number,
 *   startPosition: number,
 *   maxQty: number,
 *   trayTypeName: string
 * }} ComputedOrder
 */

/**
 * @typedef {Object} PreviewSlot
 * @property {number} position
 * @property {string} status
 * @property {string|null} orderId
 * @property {string|null} modelName
 * @property {string|null} reportModelName
 */

/**
 * @typedef {Object} PreviewResult
 * @property {PreviewSlot[]} tray1Slots
 * @property {PreviewSlot[]} tray2Slots
 * @property {string[]} errors
 */

/**
 * @typedef {Object} SlotStatus
 * @property {number} slotIndex
 * @property {boolean} isOccupied
 * @property {string=} shelfLayoutName
 * @property {number=} orderCount
 */

/**
 * @typedef {Object} DeclarationHistoryItem
 * @property {number} id
 * @property {string} mode
 * @property {string} status
 * @property {number|null} machineSlotIndex
 * @property {number|null} stagingSlotIndex
 * @property {string=} shelfLayoutName
 * @property {number=} orderCount
 * @property {string=} createdByUsername
 * @property {string=} pickedByAgvName
 * @property {string=} pickedByAgvId
 * @property {string=} createdAtUtc
 * @property {number=} productionDurationSeconds
 */

export const SHELF_DECLARATION_TYPES = true;
