/**
 * @typedef {Object} OrderDraft
 * @property {number|string} key
 * @property {string} orderId
 * @property {string} modelName
 * @property {string=} reportModelName
 * @property {0|1|null=} orderInput
 * @property {boolean=} isAutoGeneratedOrder
 * @property {number|null} quantity
 * @property {number=} jigType
 * @property {number=} inputThickness
 * @property {number=} jigHeightMm
 */

/**
 * @typedef {OrderDraft & {
 *   orderSequence: number,
 *   cartPositionIndex: number,
 *   maxQty: number,
 *   placements: Array<{cartPositionIndex: number, quantity: number}>
 * }} ComputedOrder
 */

/**
 * @typedef {Object} PreviewSlot
 * @property {number} position
 * @property {string} status
 * @property {string|null} orderId
 * @property {string|null} modelName
 * @property {string|null} reportModelName
 */

/**
 * @typedef {Object} PreviewResult
 * @property {PreviewSlot[]} positions
 * @property {string[]} errors
 */

/**
 * @typedef {Object} SlotStatus
 * @property {number} slotIndex
 * @property {boolean} isOccupied
 * @property {string=} shelfLayoutName
 * @property {number=} orderCount
 */

/**
 * @typedef {Object} DeclarationHistoryItem
 * @property {number} id
 * @property {string} mode
 * @property {string} status
 * @property {number|null} machineSlotIndex
 * @property {number|null} stagingSlotIndex
 * @property {string=} shelfLayoutName
 * @property {number=} orderCount
 * @property {string=} createdByUsername
 * @property {string=} pickedByAgvName
 * @property {string=} pickedByAgvId
 * @property {string=} createdAtUtc
 * @property {number=} productionDurationSeconds
 */

export const SHELF_DECLARATION_TYPES = true;
